### ISSUE TITLE
Navigation drawer animation affects rendering

### ISSUE THREAD

**Issue by GoelBiju** [ral-facilities/scigateway#145]
**Description**:
At the moment we are using a "push" animation which adjusts the width of the page content, as a result. Each opening and closing of the navigation drawer sends a re-render message to the plugin asking for it re-render to adjust for the change in width. 

This causes further issues especially when tables in tabs i.e. download-cart and download-status tables reload and fetch data with each render.

An example of the issue is shown below. You can see that the data is being reloaded with opening and closing of the navigation drawer.

![downloadtable](https://user-images.githubusercontent.com/16869075/73672370-a381e000-46a4-11ea-97b7-6495304c20ca.gif)

Preferrably we would want a navigation drawer which does not affect the rendering of the plugin, possibly an overlay animation.

**Acceptance criteria**:
- [ ] Overlay animation for the navigation drawer which does not affect rendering of the page contents.

**Comment by louise-davies** [comment]
Upon investigation, this is due to how the Routing component renders the plugin container components. When the nav bar opens, this modifies the styles of the Routing container so as to correctly size the rest of the app - however since the plugins are defined inline this causes a full unmount/re-mount. This can be fixed by using `PureComponent` or `React.memo` etc. so that the plugins only rerender when given a new plugin config. This also requires changes to how the plugin rerender action is sent but it's not too difficult.

However, I would be interested in what people's thoughts are on how the navbar works - i.e. it is a persistent variant of the Material UI drawer (https://material-ui.com/components/drawers/#persistent-drawer). However, we would not need to worry about plugin rerendering + resizing if we used a temporary drawer (https://material-ui.com/components/drawers/#temporary-drawer), which would in instead overlay the plugins.

Do people prefer how a temporary drawer looks + works over the persistent variety or vice versa?

@agbeltran @GoelBiju @esl-lewis @stuartpullinger @frazzleuk @jeremyspencer39171 @adalator

**Comment by GoelBiju** [comment]
@louise-davies personally I prefer the look of the temporary drawer. The way it overlays the plugin container is a lot more cleaner than how the persistent one pushes the plugin content to the side.

**Comment by jeremyspencer39171** [comment]
We would rather have the nav bar open unless the user wants to close it. I don't think it matters to us if the nav bar is temporary or permanent (we don't have a wide table to display), but we would like it to start open. Also might look better if the nav bar doesn't shuffle the title bar over, it doesn't reveal anything up there anyway.

Why does it fetch new data when it resizes? Isn't it just the same as resizing your window?

**Comment by louise-davies** [comment]
@jeremyspencer39171 

> Why does it fetch new data when it resizes? Isn't it just the same as resizing your window?

That's what this issue is about - the nav bar opening/closing is forcing the plugins to completely unmount & remount vs just rerender (unmounting & mounting causes the data fetching to be restarted, if it just rerenders then that doesn't affect things other than visuals).

> We would rather have the nav bar open unless the user wants to close it. I don't think it matters to us if the nav bar is temporary or permanent (we don't have a wide table to display)

It does matter to you if the nav bar is temporary because that contradicts your previous "We would rather have the nav bar open unless the user wants to close it" - a temporary nav drawer is only open when a user is actively navigating (e.g. you can only click items in the drawer, if you click away from the drawer it closes). A persistent one is open/closes until a user decides to toggle it manually.

>  but we would like it to start open.

This would require a refactor as currently the nav bar isn't even visible if a user hasn't logged in and is therefore closed until they log in. I presume we would be able set it to be open after a user logs in.

> Also might look better if the nav bar doesn't shuffle the title bar over, it doesn't reveal anything up there anyway.

The problem would be where to "put" the nav bar - the open/close button lives up on the title bar and so if we don't move the title bar then it would instead just render over the title (I don't know whether this would look better or worse).
