### ISSUE TITLE
Add info about registering/forgot password/help signing in 

### ISSUE THREAD

**Issue by agbeltran** [ral-facilities/scigateway#864]
**Description**:
The login page should include information about different options for signing in. 

For ISIS, we should include links to the different options within the user office (https://users.facilities.rl.ac.uk/auth/) so that users can sort out login issues that way.

**Acceptance criteria**:
- [x] Add link to support 'Forgot password?' option
- [x] Add link to information to register
- [x] Add link to help for signing in

**Comment by mattjSTFC** [comment]
Preview link for an updated login layout:

https://preview.uxpin.com/ee9832eb8102ff6013aad58becab3ea162682ce9#/pages/145182791/simulate/no-panels

- Made the form elements wider to use the space better. I've always felt it is quite constrictive but there maybe a reason for this
- Added 12px or 24px spacing between sections. So after the "Sign in" heading and forgotten password made it 24px. Everything else is 12px
- Added the word "your" into "Forgotten password"
- Add a horizontal border with the word "or" separator to make it flow. So ... "Need help signing in or don't have an account? Sign up now" Added "now" to give some urgency to it
- Made the "sign in" heading and button bold to give it some weight. Otherwise it's all a regular font
- Change the orange icon colour to be blue so it matches the sign in button top right

**Spacing suggestions**

![image](https://user-images.githubusercontent.com/56403718/146186394-42a435de-a636-4a29-9d71-fca7520de231.png)

**Comment by joshuadkitenge** [comment]
![Screenshot 2021-12-16 135634](https://user-images.githubusercontent.com/83226114/146385255-d8854e87-706b-4bb6-8e5f-4f5267390670.png)

**Comment by mattjSTFC** [comment]
That looks soooooooooooo good ☝️😍

**Comment by joshuadkitenge** [comment]
![Screenshot 2021-12-16 142114](https://user-images.githubusercontent.com/83226114/146389154-f220139f-aa39-493d-9550-38b0dd7d0617.png)

**Comment by mattjSTFC** [comment]
Why is there such a big gap between Sign in and Username?

**Comment by joshuadkitenge** [comment]
![loginpage](https://user-images.githubusercontent.com/83226114/146390447-d7d2ccb3-f74c-4745-8c45-6b96dfa09311.gif)

**Comment by joshuadkitenge** [comment]
> Why is there such a big gap between Sign in and Username?

I can make it smaller. 

![Screenshot 2021-12-16 145021](https://user-images.githubusercontent.com/83226114/146393921-4caee0d5-8b50-4e39-b81f-24934639d564.png)

**Comment by mattjSTFC** [comment]
Ahhh was it because the label moved up on focus? What's the gap now?

**Comment by joshuadkitenge** [comment]
I changed the gap to 24px, but I think another component already had spacing 12px, so it made it 36px instead of 24 px

**Comment by joshuadkitenge** [comment]
so the gap now should be 24 px now, but I'll double-check now

**Comment by joshuadkitenge** [comment]
![Screenshot 2021-12-16 152004](https://user-images.githubusercontent.com/83226114/146398690-f3c60e13-e421-40ae-bee2-c2b53bb06296.png)

@mattjSTFC

**Comment by mattjSTFC** [comment]
Happy days on the spacing! ⭐ Can I ask for one more change? 😬 Can the gap between the padlock icon and the heading be reduced? It looks a little spaced out and would be better if they were closer as they are connected. Is it 12px?

**Comment by joshuadkitenge** [comment]
![Screenshot 2021-12-16 153831](https://user-images.githubusercontent.com/83226114/146401744-f161b13c-69df-43d1-b6b9-187b2ac4bca4.png)

@mattjSTFC  it wasn't 12px. I inspected everything now. Everything should have the right spacing.

**Comment by mattjSTFC** [comment]
Thank you 🌟
