### ISSUE TITLE
Fix cookie warning in Firefox

### ISSUE THREAD

**Issue by louise-davies** [ral-facilities/scigateway#975]
**Description**:
Firefox displays a warning about google analytics cookies being set with the wrong same site value. We should fix this via adding this config to the react-ga initialisation

```
ReactGA.initialize(trackingID, {
    gaOptions: {
        cookieFlags: 'SameSite=None;Secure'
     }
});
```

Or maybe samesite lax - investigate what the samesite property is and which setting is appropriate

**Acceptance criteria**:
- [ ] No warning in firefox

**Comment by joshuadkitenge** [comment]
@louise-davies 

- The console is giving this warning message
<br><br>

![image](https://user-images.githubusercontent.com/83226114/157021320-df89818d-54cf-4709-9022-360f066635dd.png)

- I think this is due to the ReactGA.initialize being defined  in the cookie consent instead of the App.tsx (when I moved React.GA.initialize into the App.tsx this error didn't appear in the console)

- also, when I added  your suggested changes it still seems to still give me a warning message 

<br><br>

![image](https://user-images.githubusercontent.com/83226114/157022233-10819977-c551-482b-aa8e-527e6b10a4c4.png)

- I also tried "Samesite=Lax;'  and the warning message was still in the console

**Comment by louise-davies** [comment]
The second cookie warning message is warning about a different cookie - "cookie-consent" which is one we set and not a GA cookie - so the fix did work for the GA cookies! See here: https://github.com/js-cookie/js-cookie#samesite on how to set samesite for js-cookie cookies.

re: the initialize call, the only problem is that we can't initialise analytics until we have consent from the user. If you can move it to `App.tsx` and it still only initialises once we have consent then move it, otherwise we'll have to live with the warning
